version: '3'

tasks:
  rector:
    cmds:
      - vendor/bin/rector --dry-run

  rector:fix:
    cmds:
      - vendor/bin/rector

  ccs:
    cmds:
      - vendor/bin/pint --config pint.json -v --test

  ccs:fix:
    cmds:
      - vendor/bin/pint --config pint.json

  prettier:
    cmds:
      - npm run format

  prettier:fix:
    cmds:
      - npm run format:fix

  test:
    cmds:
      - php artisan test {{.CLI_ARGS}}

  ci:
    cmds:
      - task: rector
      - task: ccs
      - task: prettier
      - task: test

  fix:
    cmds:
      - task: rector:fix
      - task: ccs:fix
      - task: prettier:fix
